In [9]:
%matplotlib inline

In [10]:
import torch

# 创建张量并设置requires_grad=True，表示需要追踪计算梯度的历史
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [11]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [12]:
# 结果`y` 已经被计算出来了，所以 `y.grad_fn`已经被自动生成
print(y.grad_fn)

In [13]:
# 对y进行一个操作
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [14]:
# .requires_grad(...)可以改变现有张量的requires_grad属性。如果没有指定的话，默认是False。
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


# 梯度
反向传播 因为 out是一个纯量（scalar），out.backward() 等于out.backward(torch.tensor(1))

In [15]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
