## 张量
Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact,GPus are designed to run tensors.

In [5]:
from __future__ import print_function
import torch

# create a 5x3 tensor without init
x = torch.empty(5,3)
print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])


In [6]:
# create a tensor with random init
x = torch.rand(5,3)
x

tensor([[0.9581, 0.5458, 0.2260],
        [0.0710, 0.3298, 0.3651],
        [0.7684, 0.0709, 0.7749],
        [0.4844, 0.5160, 0.6962],
        [0.2862, 0.0773, 0.2889]])

In [7]:
# create a tensor with init with given value 0, type is long
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
# create a tensor init by given data
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [9]:
# create a tensor like x
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x1 = torch.randn_like(x, dtype=torch.float)
print(x1)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0615, -1.1388, -1.1876],
        [ 0.5369, -0.9052,  0.1725],
        [ 1.1397,  1.2928, -0.1895],
        [-0.3736, -1.6036,  1.0168],
        [ 0.0374, -0.5160,  0.6283]])


In [21]:
# get size, return list
print(x.size())
x.shape[0]
x.size()[1]

# Torch.Size() return a tuple
shape_tuple = torch.Size([5,3])
shape_tuple

torch.Size([5, 3])


torch.Size([5, 3])

# Operations

In [25]:
# add
y = torch.rand(5,3)
x + y
torch.add(x, y)

# give result as parameter
result = torch.empty(5,3)
torch.add(x, y, out=result)
result

tensor([[1.3348, 1.7943, 1.0477],
        [1.5526, 1.3504, 1.6536],
        [1.0176, 1.2053, 1.8569],
        [1.8766, 1.3432, 1.7663],
        [1.7281, 1.9307, 1.9126]])

In [27]:
# add in place
zero = torch.zeros(x.size())
print(zero)
zero.add_(x)
zero


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# Note
任何以_结尾的函数，如add_，都是inplace操作，会改变原张量。

In [28]:
print(zero[:,1])

tensor([1., 1., 1., 1., 1.])


In [30]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())
t = x.view(2,8)
print(t.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
torch.Size([2, 8])


# If one of the sizes of the tensor is set to -1, the size of that dimension is inferred from the size of the other dimensions.

In [31]:
x = torch.randn(1,2,3)
print(x)
y = x.view(-1,6)
print(y)


tensor([[[-0.6386, -2.2023,  0.8839],
         [ 1.2778, -2.8884, -0.1644]]])
tensor([[-0.6386, -2.2023,  0.8839,  1.2778, -2.8884, -0.1644]])


In [32]:
# reshape
x = torch.randn(4,4)
y = x.view_as(x)
print(y)

tensor([[-1.1990,  1.1608, -2.4118,  1.4835],
        [-0.8905, -1.1355,  0.4029, -0.6482],
        [ 0.6338,  0.6073, -1.4107,  0.8376],
        [-1.5244,  0.0929,  0.0928, -1.1989]])


In [37]:
# 转置
x = torch.randn(4,4)
print(x)

x.t_()
print(x)

# 矩阵乘法
x = torch.randn(5,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print(z)

print(x.mm(y))

print(x * y) # element-wise

tensor([[-0.9475, -0.2225,  1.4373,  1.4915],
        [ 0.5894,  0.8399, -0.9881,  2.0757],
        [ 0.8874, -0.2762,  0.3295,  0.5656],
        [-1.4507,  0.2237,  0.2569, -0.9521]])
tensor([[-0.9475,  0.5894,  0.8874, -1.4507],
        [-0.2225,  0.8399, -0.2762,  0.2237],
        [ 1.4373, -0.9881,  0.3295,  0.2569],
        [ 1.4915,  2.0757,  0.5656, -0.9521]])
tensor([[ 0.1744, -0.0917],
        [ 0.3840, -0.0552],
        [-0.1390,  0.4604],
        [ 0.1322,  0.2345],
        [-0.3813,  0.3789]])
tensor([[ 0.1744, -0.0917],
        [ 0.3840, -0.0552],
        [-0.1390,  0.4604],
        [ 0.1322,  0.2345],
        [-0.3813,  0.3789]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [39]:
# 所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到 NumPy 的转换. CUDA 张量
if torch.cuda.is_available():
    device = torch.device("cuda")  # a CUDA 设备对象
    y = torch.ones_like(x, device=device) # 直接从GPU创建张量
    x = x.to(device) # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
